# Do NOT update manually; changes here will be overwritten by Copier
_commit: 3f61c69
_src_path: gh:Fenix-ERP/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: false
github_check_license: true
github_enable_codecov: false
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_version: 14.0
org_name: Fenix-ERP
org_slug: Fenix-ERP
rebel_module_groups: []
repo_description: Development of customized modules to solve the commercial flow of
    Imporpalac
repo_name: Custom modules for Imporpalac
repo_slug: custom-imporpalac
repo_website: https://github.com/Fenix-ERP/custom-imporpalac
travis_apt_packages: []
travis_apt_sources: []

